version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:80"
      - "1443:443"
    env_file:
      - ./.env
    volumes:
      - /etc/letsencrypt/live/mybricklog.com:/etc/nginx/ssl:ro
      - user_uploads:/usr/share/nginx/html/images/users
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network
      - shared_public_net
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "1.0"
        reservations:
          memory: 256m
          cpus: "0.5"
    restart: unless-stopped

  backend:
    build:
      context: ./lego-api
      dockerfile: Dockerfile
    ports:
      - "1080:80"
    env_file:
      - ./.env.production
    volumes:
      - user_uploads:/var/www/html/public/images/users
    networks:
      - app-network
      - shared_public_net
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"
        reservations:
          memory: 128m
          cpus: "0.25"
    restart: unless-stopped

volumes:
  user_uploads:

networks:
  app-network:
    driver: bridge
  shared_public_net:
    external: true