version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:80"
      - "1443:443"
    volumes:
      - /etc/letsencrypt/live/mybricklog.com:/etc/nginx/ssl:ro
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network
      - shared_public_net
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "1.0"
        reservations:
          memory: 256m
          cpus: "0.5"
    restart: unless-stopped

  backend:
    build:
      context: ./lego-api
      dockerfile: Dockerfile
    ports:
      - "1080:80"
    environment:
      - MBL_SQL_HOST=${MBL_SQL_HOST}
      - MBL_SQL_USER=${MBL_SQL_USER}
      - MBL_SQL_PASS=${MBL_SQL_PASS}
      - MBL_SQL_PORT=${MBL_SQL_PORT}
    networks:
      - app-network
      - shared_public_net
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"
        reservations:
          memory: 128m
          cpus: "0.25"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
  shared_public_net:
    external: true